POST {{baseUrl}}/auth/login/password
Content-Type: application/json

{
  "username": "min",
  "password": "c663b11dff4be0badcf652212a2c1102"
}


> {% client.global.set("admin_token", response.body.data.authority); %}

###
POST {{baseUrl}}/auth/login/password
Content-Type: application/json

{
  "username": "LisiHotel",
  "password": "e10adc3949ba59abbe56e057f20f883e"
}

> {% client.global.set("hotel_token", response.body.data.authority); %}

###
POST {{baseUrl}}/auth/login/password
Content-Type: application/json

{
  "username": "13813712345",
  "password": "e10adc3949ba59abbe56e057f20f883e"
}

> {% client.global.set("port_token", response.body.data.authority); %}

###
POST {{baseUrl}}/location/addLocation
Content-Type: application/json
Authorization: {{admin_token}}

{
  "address": "",
  "city": "深圳",
  "locationName": "福田口岸",
  "locationType": "PORT",
  "province": "广东"
}

###
POST {{baseUrl}}/location/getLocationList
Content-Type: application/json
Authorization: {{admin_token}}

{
  "pageIndex": 1,
  "pageSize": 10
}

###
POST {{baseUrl}}/location/getLocationDropDown
Content-Type: application/json
Authorization: {{admin_token}}

{
  "type": "HOTEL"
}

###
POST {{baseUrl}}/location/updateLocation
Content-Type: application/json
Authorization: {{admin_token}}

{
  "address": "香洲区101号",
  "city": "珠海",
  "id": 3,
  "locationName": "荔湾酒店",
  "province": "广东"
}

###
POST {{baseUrl}}/user/addUser
Content-Type: application/json
Authorization: {{admin_token}}

{
  "realName": "王帅",
  "role": "PORT_USER",
  "username": "wangshuai"
}

###
POST {{baseUrl}}/user/getUserList
Content-Type: application/json
Authorization: {{admin_token}}

{
  "pageIndex": 1,
  "pageSize": 10
}

###
POST {{baseUrl}}/user/updatePassword
Content-Type: application/json
Authorization: {{admin_token}}

{
  "id": 6,
  "newPassword": "e10adc3949ba59abbe56e057f20f883e"
}

###
POST {{baseUrl}}/user/updateUserInfo
Content-Type: application/json
Authorization: {{hotel_token}}

{
  "newPassword": "e10adc3949ba59abbe56e057f20f883e"
}

###
POST {{baseUrl}}/user/disableUser/6
Authorization: {{admin_token}}

###
POST {{baseUrl}}/user/enableUser/6
Authorization: {{admin_token}}

###
POST {{baseUrl}}/traveler/addTraveler
Content-Type: application/json
Authorization: {{admin_token}}

{
  "birthday": "1997-04-15",
  "cardNumber": "441900199704152423",
  "gender": "MALE",
  "name": "王大炮",
  "nationality": "中国",
  "portId": 4,
  "portName": "横琴口岸",
  "province": "广东"
}

###
POST {{baseUrl}}/traveler/getTravelerList
Content-Type: application/json
Authorization: {{admin_token}}

{
  "pageIndex": 1,
  "pageSize": 10
}

###
POST {{baseUrl}}/traveler/deleteTraveler/1123
Authorization: {{admin_token}}

###
POST {{baseUrl}}/traveler/getPersonalArchive/2
Authorization: {{admin_token}}

###
POST {{baseUrl}}/trainRecord/addTrain
Content-Type: application/json
Authorization: {{admin_token}}

{
  "carNumber": "粤S3388Q",
  "driverName": "杨过",
  "driverPhone": "13817344567",
  "followerName": "郭襄",
  "followerPhone": "13817344460",
  "hotelId": 2,
  "hotelName": "荔湾酒店",
  "portId": 3,
  "portName": "横琴口岸"
}

###
POST {{baseUrl}}/trainRecord/getTrainList/port
Content-Type: application/json
Authorization: {{admin_token}}

{
  "pageIndex": 1,
  "pageSize": 10,
  "portId": 4
}

###
POST {{baseUrl}}/traveler/getNotBoardedTravelerList
Content-Type: application/json
Authorization: {{admin_token}}

{
  "pageIndex": 1,
  "pageSize": 10,
  "portId": 4
}

###
POST {{baseUrl}}/trainRecord/board
Content-Type: application/json
Authorization: {{admin_token}}

{
  "trainId": 2,
  "travelerIds": [
    2,
    3
  ]
}

###
POST {{baseUrl}}/trainRecord/deleteTrain/22
Content-Type: application/json
Authorization: {{admin_token}}


###
POST {{baseUrl}}/trainRecord/depart/2
Authorization: {{admin_token}}

###
POST {{baseUrl}}/trainRecord/getTrainList/arriving
Content-Type: application/json
Authorization: {{admin_token}}

{
  "pageIndex": 1,
  "pageSize": 10
}

###
POST {{baseUrl}}/trainRecord/acceptTrain
Content-Type: application/json
Authorization: {{admin_token}}

{
  "trainIds": [
    2
  ]
}


###
POST {{baseUrl}}/traveler/getTravelerListByTrain
Content-Type: application/json
Authorization: {{admin_token}}

{
  "pageIndex": 1,
  "pageSize": 10,
  "trainId": 2
}

###
POST {{baseUrl}}/trainRecord/getTrainList/arrived
Content-Type: application/json
Authorization: {{admin_token}}

{
  "pageIndex": 1,
  "pageSize": 10
}

###
POST {{baseUrl}}/traveler/getTravelerList/hotel
Content-Type: application/json
Authorization: {{admin_token}}

{
  "hotelId": 2,
  "pageIndex": 1,
  "pageSize": 10
}

###
POST {{baseUrl}}/traveler/getNotQuarantineTravelerList
Content-Type: application/json
Authorization: {{admin_token}}

{
  "pageIndex": 1,
  "pageSize": 10
}

###
POST {{baseUrl}}/traveler/startQuarantine
Content-Type: application/json
Authorization: {{admin_token}}

{
  "startTime": "2021-03-20",
  "travelerIds": [
    2,
    3
  ]
}

###
POST {{baseUrl}}/temperature/getTemperatureRecordList
Content-Type: application/json
Authorization: {{admin_token}}

{
  "date": "2021-03-20",
  "pageIndex": 1,
  "pageSize": 10
}

###
POST {{baseUrl}}/temperature/recordTemperature
Content-Type: application/json
Authorization: {{admin_token}}

[
  {
    "id": 1,
    "isNormal": 1,
    "temperature": "37.1"
  },
  {
    "id": 2,
    "isNormal": 1,
    "temperature": "37.1"
  }
]

###
POST {{baseUrl}}/traveler/endQuarantine/2
Authorization: {{admin_token}}

###
POST {{baseUrl}}/traveler/getHotelData
Content-Type: application/json
Authorization: {{admin_token}}

{
  "hotelId": 2
}

###
POST {{baseUrl}}/traveler/getNumberTrend
Content-Type: application/json
Authorization: {{admin_token}}

{}

###
POST {{baseUrl}}/traveler/getNationalityStatistics
Content-Type: application/json
Authorization: {{admin_token}}

{}