POST {{baseUrl}}/auth/login/password
Content-Type: application/json

{
  "username": "min",
  "password": "e10adc3949ba59abbe56e057f20f883e"
}


> {% client.global.set("admin_token", response.body.data.authority); %}

###
POST {{baseUrl}}/location/addLocation
Content-Type: application/json
Authorization: {{admin_token}}

{
  "address": "香洲区环岛东路",
  "city": "珠海",
  "locationName": "横琴口岸",
  "locationType": "PORT",
  "province": "广东"
}

###
POST {{baseUrl}}/location/getLocationList
Content-Type: application/json
Authorization: {{admin_token}}

{
  "pageIndex": 1,
  "pageSize": 10
}

###
POST {{baseUrl}}/location/getLocationDropDown
Content-Type: application/json
Authorization: {{admin_token}}

{
  "role": "PORT_USER",
  "province": "广东"
}

###
POST {{baseUrl}}/location/updateLocation
Content-Type: application/json
Authorization: {{admin_token}}

{
  "address": "香洲区101号",
  "city": "珠海",
  "id": 3,
  "locationName": "荔湾酒店",
  "province": "广东"
}

###
POST {{baseUrl}}/user/addUser
Content-Type: application/json
Authorization: {{admin_token}}

{
  "locationId": 4,
  "realName": "张三",
  "role": "PORT_USER",
  "username": "13813712345"
}

###
POST {{baseUrl}}/user/getUserList
Content-Type: application/json
Authorization: {{admin_token}}

{
  "pageIndex": 1,
  "pageSize": 10
}